[versions]

kotlin = "2.3.20"
agp = "8.10.1"
compose = "1.10.3"
androidx-activityCompose = "1.13.0"
dokka = "2.0.0"
maven-publish = "0.34.0"
startupRuntime = "1.2.0"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
